#!/bin/bash

set -e

if [[ -n "$PTM_DEBUG" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Build Docker images.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
        exit
    fi

    docker build -t pytorch_models -f Dockerfile .
fi
